name: docs
on:
    push:
        branches:
            - master
env:
    DOIT_NUM_PROCESS: 0
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repository
            uses: actions/checkout@v2
          - name: install python
            uses: actions/setup-python@v1
            with:
                python-version: "3.10"
          - name: install ubuntu requirements
            run: |
                sudo apt update
                sudo apt install -q -y plantuml
          - name: install python requirements
            run: |
                python -m pip install --upgrade pip
                pip install -e '.[dev]'
          - name: doit docs
            run: doit docs
          - name: create CNAME
            if: github.repository == 'hat-open/hat-syslog'
            run: |
                 echo "hat-syslog.hat-open.com" > build/docs/CNAME
          - name: deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build/docs
                publish_branch: gh-pages
                force_orphan: true
